import uuid

from src.books.schemas import BookBase

books: list[BookBase] = [
    BookBase(**book)
    for book in [
        {
            "uid": uuid.uuid4(),
            "title": "Think Python",
            "author": "Allen B. Downey",
            "publisher": "O'Reilly Media",
            "published_date": "2021-01-01",
            "page_count": 1234,
            "language": "English",
        },
        {
            "uid": uuid.uuid4(),
            "title": "Clean Code",
            "author": "Robert C. Martin",
            "publisher": "Prentice Hall",
            "published_date": "2008-08-01",
            "page_count": 464,
            "language": "English",
        },
        {
            "uid": uuid.uuid4(),
            "title": "The Pragmatic Programmer",
            "author": "Andrew Hunt",
            "publisher": "Addison-Wesley",
            "published_date": "1999-10-30",
            "page_count": 352,
            "language": "English",
        },
        {
            "uid": uuid.uuid4(),
            "title": "Design Patterns",
            "author": "Erich Gamma",
            "publisher": "Addison-Wesley",
            "published_date": "1994-10-21",
            "page_count": 395,
            "language": "English",
        },
        {
            "uid": uuid.uuid4(),
            "title": "Refactoring",
            "author": "Martin Fowler",
            "publisher": "Addison-Wesley",
            "published_date": "2018-11-19",
            "page_count": 448,
            "language": "English",
        },
        {
            "uid": uuid.uuid4(),
            "title": "Deep Work",
            "author": "Cal Newport",
            "publisher": "Grand Central Publishing",
            "published_date": "2016-01-05",
            "page_count": 304,
            "language": "English",
        },
        {
            "uid": uuid.uuid4(),
            "title": "Atomic Habits",
            "author": "James Clear",
            "publisher": "Avery",
            "published_date": "2018-10-16",
            "page_count": 320,
            "language": "English",
        },
        {
            "uid": uuid.uuid4(),
            "title": "The Lean Startup",
            "author": "Eric Ries",
            "publisher": "Crown Business",
            "published_date": "2011-09-13",
            "page_count": 336,
            "language": "English",
        },
        {
            "uid": uuid.uuid4(),
            "title": "Zero to One",
            "author": "Peter Thiel",
            "publisher": "Crown Business",
            "published_date": "2014-09-16",
            "page_count": 224,
            "language": "English",
        },
        {
            "uid": uuid.uuid4(),
            "title": "You Don't Know JS Yet",
            "author": "Kyle Simpson",
            "publisher": "Independently Published",
            "published_date": "2020-01-28",
            "page_count": 143,
            "language": "English",
        },
        {
            "uid": uuid.uuid4(),
            "title": "Eloquent JavaScript",
            "author": "Marijn Haverbeke",
            "publisher": "No Starch Press",
            "published_date": "2018-12-04",
            "page_count": 472,
            "language": "English",
        },
        {
            "uid": uuid.uuid4(),
            "title": "Introduction to Algorithms",
            "author": "Thomas H. Cormen",
            "publisher": "MIT Press",
            "published_date": "2009-07-31",
            "page_count": 1312,
            "language": "English",
        },
        {
            "uid": uuid.uuid4(),
            "title": "Cracking the Coding Interview",
            "author": "Gayle Laakmann McDowell",
            "publisher": "CareerCup",
            "published_date": "2015-07-01",
            "page_count": 687,
            "language": "English",
        },
        {
            "uid": uuid.uuid4(),
            "title": "The Clean Coder",
            "author": "Robert C. Martin",
            "publisher": "Prentice Hall",
            "published_date": "2011-05-13",
            "page_count": 256,
            "language": "English",
        },
        {
            "uid": uuid.uuid4(),
            "title": "Domain-Driven Design",
            "author": "Eric Evans",
            "publisher": "Addison-Wesley",
            "published_date": "2003-08-30",
            "page_count": 560,
            "language": "English",
        },
        {
            "uid": uuid.uuid4(),
            "title": "Working Effectively with Legacy Code",
            "author": "Michael Feathers",
            "publisher": "Prentice Hall",
            "published_date": "2004-09-30",
            "page_count": 456,
            "language": "English",
        },
        {
            "uid": uuid.uuid4(),
            "title": "Soft Skills",
            "author": "John Sonmez",
            "publisher": "Manning Publications",
            "published_date": "2014-11-11",
            "page_count": 504,
            "language": "English",
        },
        {
            "uid": uuid.uuid4(),
            "title": "Code Complete",
            "author": "Steve McConnell",
            "publisher": "Microsoft Press",
            "published_date": "2004-06-09",
            "page_count": 960,
            "language": "English",
        },
        {
            "uid": uuid.uuid4(),
            "title": "The Mythical Man-Month",
            "author": "Frederick P. Brooks Jr.",
            "publisher": "Addison-Wesley",
            "published_date": "1995-08-12",
            "page_count": 322,
            "language": "English",
        },
        {
            "uid": uuid.uuid4(),
            "title": "Head First Design Patterns",
            "author": "Eric Freeman",
            "publisher": "O'Reilly Media",
            "published_date": "2004-10-25",
            "page_count": 694,
            "language": "English",
        },
    ]
]
