"""add review table

Revision ID: 4625a2c9215d
Revises: 9d1176aecfbb
Create Date: 2026-03-27 14:09:40.339643

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4625a2c9215d"
down_revision: Union[str, Sequence[str], None] = "9d1176aecfbb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reviews",
        sa.Column("user_uid", sa.Uuid(), nullable=False),
        sa.Column("book_uid", sa.Uuid(), nullable=False),
        sa.Column("review_text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["book_uid"],
            ["books.uid"],
        ),
        sa.ForeignKeyConstraint(
            ["user_uid"],
            ["users.uid"],
        ),
        sa.PrimaryKeyConstraint("user_uid", "book_uid"),
    )
    # op.drop_table("playing_with_neon")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table(
    #     "playing_with_neon",
    #     sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
    #     sa.Column("name", sa.TEXT(), autoincrement=False, nullable=False),
    #     sa.Column("value", sa.REAL(), autoincrement=False, nullable=True),
    #     sa.PrimaryKeyConstraint("id", name=op.f("playing_with_neon_pkey")),
    # )
    op.drop_table("reviews")
    # ### end Alembic commands ###
